name: Create Image
on:
  push:
    branches:
      - master
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: '20.x'
      - name: Build and push the image
        run: |
          docker build -t ghcr.io/kiquetal/grpc-client-java: src/main/docker/Dockerfile.jvm
          echo ${{ secrets.GH_PAT }} | docker login -u kiquetal --password-stdin
          docker push ghcr.io/kiquetal/grpc-client-java:latest


