name: Create Image
on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: '20.x'
      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt
          cache: 'maven'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Build with Maven
        run: mvn package -DskipTests
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            file: src/main/docker/Dockerfile.jvm
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/grpc-client-java:latest-v2
