name: Create Image
on:
  push:
    branches:
      - master
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: '20.x'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Maven build the image
        run: mvn clean package -DskipTests
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            file: src/main/docker/Dockerfile.jvm
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/grpc-client-java:latest
